### ISSUE TITLE
用意したJSONファイルを返すようにしてほしい

### ISSUE THREAD

**Issue by j123** [417-develop/go-sample-project#1]
リクエスト受け付けたら、用意したJSONを返す簡単なやつ

**Comment by j123** [comment]
リクエスト受け付けたら、用意したJSONを返す簡単なやつ

**Comment by 417-develop** [comment]
e140e87 にてdevマージ済み
@j123 OKでしたらクローズお願いいたします。 🙇

**Comment by j123** [comment]
動作確認出来たのでcloseします！
