### ISSUE TITLE
エンドポイントごとに返すJSONファイルを変えたい

### ISSUE THREAD

**Issue by j123** [417-develop/go-sample-project#2]
複数のAPI作ったら、それぞれのエンドポイントごとに返すJSONファイルを変えれるようにしてほしい

**Comment by j123** [comment]
複数のAPI作ったら、それぞれのエンドポイントごとに返すJSONファイルを変えれるようにしてほしい

**Comment by 417-develop** [comment]
e140e87 にてdevマージ済み
@j123 OKでしたらクローズお願いいたします。 🙇

**Comment by j123** [comment]
動作確認出来たのでcloseします！
