### ISSUE TITLE
指定したリソースごとにJSONファイルかえたい

### ISSUE THREAD

**Issue by j123** [417-develop/go-sample-project#3]
例えば、 `GET /hoge/{id}` だったら、`id` ごとにJSONファイルを用意しておいて、リクエストに応じてレスポンスを変えたい

**Comment by 417-develop** [comment]
e140e87 にてdevマージ済み
@j123 OKでしたらクローズお願いいたします。 🙇

**Comment by j123** [comment]
ファイルを動的に読み込めることを確認出来たのでcloseします！
